api:
  kakao:
    key:
  naver:
    clientId:
    clientSecret:
spring:
  datasource:
    url: jdbc:h2:~/blog
    driverClassName: org.h2.Driver
    username:
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
